"""
Options to run the CLI interface of the easymore program
"""

import click


cli_options = {
    ('--case-name', '-n'): {
        'type': click.STRING,
        'required': False,
        'default': 'easymore_test',
        'show_default': True,
        'is_flag': False,
        'allow_from_autoenv': True,
        'help': 'Easymore experiment name',
        'show_choices': False,
    },
    ('--shapefile', '-s'): {
        'type': click.Path(exists=True, file_okay=True, dir_okay=False),
        'required': True,
        'is_flag': False,
        'allow_from_autoenv': True,
        'help': 'Path to the ESRI Shapefile',
        'show_choices': False,
    },
    ('--shapefile-id', '-si'): {
        'type': click.STRING,
        'required': True,
        'default': 'ID',
        'show_default': True,
        'is_flag': False,
        'allow_from_autoenv': True,
        'help': 'Column name corresponding to the IDs of the ESRI'
        ' Shapefile features',
        'show_choices': False,
    },
    ('--shapefile-lat', '-sl'): {
        'type': click.STRING,
        'required': False,
        'default': 'lat',
        'show_default': True,
        'is_flag': False,
        'allow_from_autoenv': True,
        'help': 'Column name corresponding to the latitude values of the'
        ' ESRI Shapefile features',
        'show_choices': False,
    },
    ('--shapefile-lon', '-sn'): {
        'type': click.STRING,
        'required': False,
        'default': 'lon',
        'show_default': True,
        'is_flag': False,
        'allow_from_autoenv': True,
        'help': 'Column name corresponding to the longtiude values of the'
        ' ESRI Shapefile features',
        'show_choices': False,
    },
    ('--variable', '-v'): {
        'type': click.STRING,
        'required': True,
        'is_flag': False,
        'allow_from_autoenv': True,
        'help': 'Variable names to be remapped from netCDF files',
        'show_choices': False,
        'multiple': True,
    },
    ('--variable-lat', '-vl'): {
        'type': click.STRING,
        'required': True,
        'default': 'lat',
        'show_default': True,
        'is_flag': False,
        'allow_from_autoenv': True,
        'help': 'Variable name corresponding to latitude values in the'
        ' netCDF files',
        'show_choices': False,
    },
    ('--variable-lon', '-vn'): {
        'type': click.STRING,
        'required': True,
        'default': 'lon',
        'show_default': True,
        'is_flag': False,
        'allow_from_autoenv': True,
        'help': 'Variable name corresponding to longitude values in the'
        ' netCDF files',
        'show_choices': False,
    },
    ('--variable-time', '-vt'): {
        'type': click.STRING,
        'required': False,
        'default': 'time',
        'show_default': True,
        'is_flag': False,
        'allow_from_autoenv': True,
        'help': 'Variable name corresponding to time-step values in the'
        ' netCDF file',
        'show_choices': False,
    },
    ('--variable-station', '-vs'): {
        'type': click.STRING,
        'required': False,
        'default': '',
        'is_flag': False,
        'allow_from_autoenv': True,
        'help': 'Variable name corresponding to station names in the'
        ' netCDF files',
        'show_choices': False,
    },
    ('--source-shapefile', '-ss'): {
        'type': click.Path(exists=True, file_okay=True),
        'required': False,
        'is_flag': False,
        'allow_from_autoenv': True,
        'help': 'Path to the source ESRI Shapefile (mostly for irregular'
        ' cases)',
        'show_choices': False,
    },
    ('--source-shapefile-lat', '-ssl'): {
        'type': click.STRING,
        'required': False,
        'default': 'lat',
        'show_default': True,
        'is_flag': False,
        'allow_from_autoenv': True,
        'help': 'Variable name corresponding to `latitude` available both'
        ' in the source netCDF file(s) and source ESRI Shapefile',
        'show_choices': False,
    },
    ('--source-shapefile-lon', '-ssn'): {
        'type': click.STRING,
        'required': False,
        'default': 'lon',
        'show_default': True,
        'is_flag': False,
        'allow_from_autoenv': True,
        'help': 'Variable name corresponding to `longitude` available'
        ' both in the source netCDF file(s) and source ESRI Shapefile',
        'show_choices': False,
    },
    ('--remapped-variable', '-rv'): {
        'type': click.STRING,
        'required': False,
        'is_flag': False,
        'allow_from_autoenv': True,
        'help': 'Variable names replacing input names read from netCDF'
        ' files',
        'show_choices': False,
        'multiple': True,
    },
    ('--remapped-var-id', '-ri'): {
        'type': click.STRING,
        'required': False,
        'default': 'ID',
        'show_default': True,
        'is_flag': False,
        'allow_from_autoenv': True,
        'help': 'Name of the `ID` variable to be used in the remapped'
        ' netCDF files',
        'show_choices': False,
    },
    ('--remapped-lat', '-rl'): {
        'type': click.STRING,
        'required': False,
        'default': 'latitude',
        'show_default': True,
        'is_flag': False,
        'allow_from_autoenv': True,
        'help': 'Name of the `lat` variable to be used in the remapped'
        ' netCDF files',
        'show_choices': False,
    },
    ('--remapped-lon', '-rn'): {
        'type': click.STRING,
        'required': False,
        'default': 'longitude',
        'show_default': True,
        'is_flag': False,
        'allow_from_autoenv': True,
        'help': 'Name of the `lon` variable to be used in the remapped'
        ' netCDF files',
        'show_choices': False,
    },
    ('--remapped-dim-id', '-rd'): {
        'type': click.STRING,
        'required': False,
        'default': 'ID',
        'show_default': True,
        'is_flag': False,
        'allow_from_autoenv': True,
        'help': 'Name of the `ID` dimension to be used in the remapped'
        ' netCDF files',
        'show_choices': False,
    },
    ('--chunk', '-u'): {
        'type': click.INT,
        'required': False,
        'default': 200,
        'show_default': True,
        'is_flag': False,
        'allow_from_autoenv': True,
        'help': 'Chunk size of the generated netCDF file(s)',
        'show_choices': False,
    },
    ('--output-dir', '-o'): {
        'type': click.Path(exists=False, dir_okay=True),
        'required': True,
        'is_flag': False,
        'allow_from_autoenv': True,
        'help': 'Output directory',
        'show_choices': False,
    },
    ('--format', '-f'): {
        'type': click.STRING,
        'required': False,
        'default': 'f8',
        'show_default': True,
        'is_flag': False,
        'allow_from_autoenv': True,
        'help': 'Sequence of variable datatype(s) based on NumPy Array'
        ' Interface Protocol',
        'show_default': True,
    },
    ('--missing-value', '-m'): {
        'type': click.INT,
        'required': False,
        'default': -9999,
        'show_default': True,
        'is_flag': False,
        'allow_from_autoenv': False,
        'help': 'Sequence of integer(s) filling missing values',
        'show_default': True,
    },
    ('--remap-csv', '-e'): {
        'type': click.Path(exists=True, file_okay=True),
        'required': False,
        'default': '',
        'is_flag': True,
        'allow_from_autoenv': True,
        'help': 'Previosuly generated remapping .csv file',
        'show_default': False,
    },
    ('--remap-file-only', '-R'): {
        'type': click.BOOL,
        'required': False,
        'default': False,
        'show_default': True,
        'is_flag': True,
        'allow_from_autoenv': False,
        'help': 'Only produce remapping .csv file',
    },
    ('--skip-checks', '-K'): {
        'type': click.BOOL,
        'required': False,
        'default': False,
        'show_default': True,
        'is_flag': True,
        'allow_from_autoenv': False,
        'help': 'Disable consistency checks over all input netCDF files',
        'show_choices': True,
        'show_default': True,
    },
    ('--clip-shapefile', '-L'): {
        'type': click.BOOL,
        'required': False,
        'default': True,
        'show_default': True,
        'is_flag': True,
        'allow_from_autoenv': False,
        'help': 'Clip source ESRI Shapefile to increase efficiency',
        'show_choices': True,
        'show_default': True,
    },
    ('--case-name-author', '-na'): {
        'type': click.STRING,
        'required': False,
        'default': 'Agent',
        'show_default': True,
        'is_flag': False,
        'allow_from_autoenv': False,
        'help': 'Easymore experiment agent',
        'show_choices': False,
    },
    ('--overwrite', '-O'): {
        'type': click.BOOL,
        'required': False,
        'default': True,
        'show_default': True,
        'is_flag': True,
        'allow_from_autoenv': False,
        'help': 'Overwrite netCDF files',
        'show_choices': True,
        'show_default': True,
    },
    ('--cache', '-c'): {
        'type': click.Path(exists=False, file_okay=False),
        'required': False,
        'default': '',
        'is_flag': False,
        'allow_from_autoenv': True,
        'help': 'Temporary directory',
        'show_choices': False,
    },
}
